DROP TABLE employee;
DROP TYPE gender;
CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
CREATE TABLE employee (
                          employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(45),
                          last_name VARCHAR(45),
                          department_id INT,
                          job_title VARCHAR(255),
                          gender gender,
                          date_of_birth DATE
);

INSERT INTO employee (first_name, last_name, department_id, job_title, gender, date_of_birth)
VALUES ('Nadya', 'Bosak', NULL ,'HR Manager', 'FEMALE', '23-02-00'),
       ('Pavel', 'Kananovich', NULL, 'Java Software Engineer', 'MALE', '10-08-00'),
       ('Andrey', 'Likhtar', NULL,'Software Engineer', 'MALE', '15-12-00'),
       ('Irina', 'Kvartalnaya', NULL,'Head of Operations', 'FEMALE', NULL),
       ('Natalia', 'Vyrva', NULL, '.NET Software Engineer', 'FEMALE', '25-11-00');